USE tresia_studio;

ALTER TABLE efectivo_detalle 
  ADD COLUMN c1000 INT DEFAULT 0,
  ADD COLUMN c500 INT DEFAULT 0,
  ADD COLUMN c200 INT DEFAULT 0,
  ADD COLUMN c100 INT DEFAULT 0,
  ADD COLUMN c50 INT DEFAULT 0,
  ADD COLUMN c20 INT DEFAULT 0,
  ADD COLUMN cm10 INT DEFAULT 0,
  ADD COLUMN cm5 INT DEFAULT 0,
  ADD COLUMN cm2 INT DEFAULT 0,
  ADD COLUMN cm1 INT DEFAULT 0,
  ADD COLUMN cm050 INT DEFAULT 0;
